-- pg_petgraph: Graph algorithms for PostgreSQL
-- Auto-generated by pgrx. DO NOT EDIT manually.

-- PageRank centrality
CREATE OR REPLACE FUNCTION pagerank(
    sources bigint[],
    targets bigint[],
    damping double precision DEFAULT 0.85,
    max_iter integer DEFAULT 100
) RETURNS TABLE(node_id bigint, score double precision)
STRICT
LANGUAGE c AS 'MODULE_PATHNAME', 'pagerank_wrapper';

-- Strongly Connected Components (Kosaraju)
CREATE OR REPLACE FUNCTION scc(
    sources bigint[],
    targets bigint[]
) RETURNS TABLE(node_id bigint, component_id bigint)
STRICT
LANGUAGE c AS 'MODULE_PATHNAME', 'scc_wrapper';

-- Betweenness Centrality (Brandes)
CREATE OR REPLACE FUNCTION betweenness(
    sources bigint[],
    targets bigint[]
) RETURNS TABLE(node_id bigint, centrality double precision)
STRICT
LANGUAGE c AS 'MODULE_PATHNAME', 'betweenness_wrapper';
